plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Name
  - key: tags.TERRAFORM
  - key: tags.SOURCE
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
python_interpreter_defined:
  vars:
    ansible_python_interpreter: /usr/bin/python3.8