plugin: aws_ec2
regions:
  - "us-east-2"
keyed_groups:
  - key: tags.Name
  - key: tags.TERRAFORM
  - key: tags.SOURCE
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
python_interpreter_defined:
  vars:
    ansible_python_interpreter: /opt/hostedtoolcache/Python/3.9.20/x64/python