---
- name: Run Node Exporter
  hosts: _monitoringPrometheus
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: "tf-keypair.pem"
  become: true
  tasks:
    - name: Run Node Exporter container
      docker_container:
        name: node_exporter
        image: quay.io/prometheus/node-exporter:latest
        state: started
        restart_policy: always
        volumes:
          - /proc:/host/proc
          - /sys:/host/sys
        network_mode: host
        command: "--path.procfs /host/proc --path.sysfs /host/sys"

    - name: Verify Node Exporter is running
      shell: |
        docker ps | grep node_exporter
      register: node_exporter_status
      failed_when: node_exporter_status.stdout == ""
      changed_when: false