name: 'Terraform'

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["terraform/**"]

  pull_request:
    branches: [main]
    paths: ["terraform/**"]

permissions:
  contents: read

jobs:
  plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Initialise project and view terraform plan
      run: |
        cd terraform
        terraform fmt
        terraform init
        terraform plan --var-file ./var_files/test.tfvars --var "cup_db_pass=${{ secrets.TF_VAR_DB_PASSWORD }}"

  deploy:
    name: Provision infra and deploy Monitoring Stack
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize project and deploy terraform
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform plan --var-file ./var_files/test.tfvars --var "cup_db_pass=${{ secrets.TF_VAR_DB_PASSWORD }}"

      - name: Preparing Stack deployment
        run: |
          mkdir -p ~/.ssh
          echo "$ANSIBLE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install boto3 and botocore in pipx environment
        run: pipx inject ansible-core boto3 botocore

      - name: Run Ansible Playbook
        run: |
            cd ansible
            ansible-playbook -i inventory_aws_ec2.yml monitoring.yaml --check
        env:
            ANSIBLE_HOST_KEY_CHECKING: 'false'
            ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.NONPROD_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.NONPROD_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1'